# Generated by Django 3.2.5 on 2021-07-14 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0003_alter_images_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=models.ImageField(default='', upload_to='profile/'),
        ),
    ]
