# Generated by Django 3.2.5 on 2021-07-14 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0005_auto_20210714_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_photo',
            field=models.ImageField(default='', upload_to='profile/'),
        ),
    ]
