# Generated by Django 3.2.5 on 2021-07-14 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0006_remove_profile_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_photo',
            field=models.ImageField(default='profile/default.jpg', upload_to='images/'),
        ),
    ]
