# Generated by Django 3.2.5 on 2021-07-14 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0007_profile_profile_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_photo',
        ),
    ]
